- name: create myid file 
  lineinfile:
    path: "{{ zookeeper_data_dir }}/myid"
    line: "{{ inventory_hostname }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    create: yes
    state: present

- name: Configure Zookeeper properties
  template:
    src: "../templates/zoo.cfg.j2"
    dest: "{{ zookeeper_installation }}/zookeeper/conf/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0644
  notify: start zookeeper

- name: Generate Zookeeper service file
  template:
    src: ../templates/zookeeper-service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0755
  notify:
    - start zookeeper
    - enable zookeeper
